name: Release

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      skip_nuget:
        description: "Skip NuGet release"
        type: boolean
        default: false
      skip_thunderstore:
        description: "Skip Thunderstore release"
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest  
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    - name: Setup TCLI
      run: dotnet tool install --global tcli

    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Install Mono on Ubuntu
      run: |
        sudo apt-get update
        sudo apt-get install -y apt-transport-https dirmngr gnupg ca-certificates
        sudo apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
        echo "deb https://download.mono-project.com/repo/ubuntu stable-focal main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
        sudo apt-get update
        sudo apt-get install -y mono-complete

    - name: Build
      run: |
        set -x
        version=$(grep -oP '(?<=PluginVersion = ")[^"]*' ./src/RoR2BepInExPack.cs)

        sed -i "0,/<PropertyGroup>/s/<PropertyGroup>/<PropertyGroup>\n    <Version>$version<\/Version>/" ./src/RoR2BepInExPack.csproj
        sed -i "0,/<PropertyGroup>/s/<PropertyGroup>/<PropertyGroup>\n    <AssemblyVersion>$version<\/AssemblyVersion>/" ./src/RoR2BepInExPack.csproj

        dotnet pack --configuration Release /p:PackageOutputPath=./ReleaseOutput /p:OutputPath=./ReleaseOutput

    - name: Push to NuGet
      if: ${{ inputs.skip_nuget == 'false' }}
      run: |
        nuget setapikey "${{ secrets.NUGET_API_KEY }}"
        nuget push ./src/ReleaseOutput/*.nupkg -Source 'https://api.nuget.org/v3/index.json'

    # Clean for Thunderstore packaging
    - name: Cleanup Before Thunderstore
      run: |
        find . -name '*.pdb' -type f -delete
        find . -name '*.deps.json' -type f -delete
        find . -name '*.nupkg' -type f -delete

    - name: Publish to Thunderstore
      if: ${{ inputs.skip_thunderstore == 'false' }}
      run: |
        echo "CWD: $(pwd)"
        ls -la
        cd thunderstore
        version=$(grep -oP '(?<=PluginVersion = ")[^"]*' ../src/RoR2BepInExPack.cs)
        sed -i "s/versionNumber = \"[^\"]*\"/versionNumber = \"$version\"/" thunderstore.toml
        tcli publish --token ${{ secrets.TCLI_AUTH_TOKEN_RISK_OF_THUNDER }}
