name: Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest  
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    - name: Setup TCLI
      run: dotnet tool install --global tcli

    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    # Install Mono on Ubuntu to run nuget.exe (due to this issue on Ubuntu 24 that hasn't been fixed yet - https://github.com/NuGet/setup-nuget/issues/168)
    - name: Install Mono on Ubuntu
      run: |
        sudo apt-get update
        sudo apt-get install -y apt-transport-https dirmngr gnupg ca-certificates
        sudo apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
        echo "deb https://download.mono-project.com/repo/ubuntu stable-focal main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
        sudo apt-get update
        sudo apt-get install -y mono-complete

    - name: Build and Publish
      run: |
        set -x

        version=$(grep -oP '(?<=PluginVersion = ")[^"]*' ./src/RoR2BepInExPack.cs)

        # nuget

        sed -i "0,/<PropertyGroup>/s/<PropertyGroup>/<PropertyGroup>\n    <Version>$version<\/Version>/" ./src/RoR2BepInExPack.csproj

        sed -i "0,/<PropertyGroup>/s/<PropertyGroup>/<PropertyGroup>\n    <AssemblyVersion>$version<\/AssemblyVersion>/" ./src/RoR2BepInExPack.csproj

        dotnet pack --configuration Release /p:PackageOutputPath=./ReleaseOutput /p:OutputPath=./ReleaseOutput

        nuget setapikey "${{ secrets.NUGET_API_KEY }}"

        nuget push ./src/ReleaseOutput/*.nupkg -Source 'https://api.nuget.org/v3/index.json'

        # thunderstore

        find . -name '*.pdb' -type f -delete
        find . -name '*.deps.json' -type f -delete
        find . -name '*.nupkg' -type f -delete

        cd thunderstore
        
        sed -i "s/versionNumber = \"[^\"]*\"/versionNumber = \"$version\"/" thunderstore.toml

        tcli publish --token ${{ secrets.TCLI_AUTH_TOKEN_RISK_OF_THUNDER }}